services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - http://localhost:5000
    profiles:
      - dev

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    #depends_on:
    #  - ai
    environment:
      - http://be:8000
    profiles:
      - dev
  
  #ai:
  #  build: ./ai
  #  ports:
  #    - '8000:8000'
  #  runtime: nvidia
  #  environment:
  #    - NVIDIA_VISIBLE_DEVICES=all
  #    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  #  volumes:
  #    - ./ai/models:/app/models